import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    flex: 1,
  },
  upper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 5,
    paddingBottom: 10,
    borderBottomStartRadius: 18,
    borderBottomEndRadius: 18,
  },
  upper1: {
    flexDirection: 'row',
  },
  back: {
    height: 48,
    width: 48,
  },
  profileimg: {
    width: 45,
    height: 45,
    borderRadius: 50,
    marginRight: 10,
    backgroundColor: '#2A7BBB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  profileimgtext: {
    color: 'white',
    fontWeight: 'bold',
  },
  nametext: {
    fontWeight: '700',
    color: 'black',
    fontSize: 20,
  },
  clocked: {
    color: 'grey',
  },
  more: {
    marginTop: -10,
    resizeMode: 'contain',
    height: 30,
    width: 30,
  },
  giftedview: {backgroundColor: '#E7EDF3', flex: 1},

  textinputstyle: {
    borderRadius: 8,
    backgroundColor: 'white',
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: 'gray',
    paddingHorizontal: 10,
  },
  containerStyle: {
    paddingVertical: 5,
  },
  add: {
    width: 30,
    height: 30,
    marginLeft: 10,
    marginVertical: 5,
    backgroundColor: 'gray',
    borderRadius: 50,
  },
  send: {
    width: 30,
    height: 30,
  },
  sendCont: {
    marginRight: 10,
    marginBottom: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    height: '60%',
    paddingHorizontal: 10,
    paddingVertical: 30,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  emojiList: {
    marginBottom: 20,
  },
  emoji: {
    fontSize: 30,
    marginHorizontal: 23,
  },
  listview: {
    flexDirection: 'row',
    paddingHorizontal: 24,
  },
  lineView: {
    borderBottomWidth: 0.5,
    marginHorizontal: 24,
    marginVertical: 24,
  },
  chattext: {
    paddingLeft: 12,
    color: '#3a4f5f',
    fontSize: 15,
  },
  delete: {
    height: 20,
    width: 25,
    resizeMode: 'contain',
  },
  deletetext: {
    color: 'red',
    paddingLeft: 12,
    fontSize: 15,
  },
  reactionContainer: {
    backgroundColor: 'beige',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 360,
    paddingVertical: 10,
    paddingHorizontal:5,
    marginTop: -5,
    borderRadius: 20,
    marginRight: 10,
    marginBottom: 5,
  },
  reactionEmoji: {
    fontSize: 18,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer1: {
    width: 346,
    height: 300,
    backgroundColor: 'white',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 60,
  },
  accountText: {
    marginTop: 16,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    color: '#0B1721',
  },
  modalText: {
    color: '#60707D',
    textAlign: 'center',
    fontSize: 13,
    fontWeight: '400',
    marginTop: 6,
    marginBottom: 28,
  },
  primaryCont: {
    backgroundColor: 'rgba(42, 123, 187, 1)',
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  primaryCont1: {
    backgroundColor: '#d3d3d3',
    marginHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  primary: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  primary1: {
    color: '#414a4c',
    fontWeight: '600',
    fontSize: 14,
  },
  deleteiconview: {
    backgroundColor: '#ffc1c3',
    borderRadius: 80,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
