const Icons = {
    
  white: require('./icons/White.png'),
  landingpage:require('./icons/LandingPage.png'),
    account:require('./icons/account.png'),
    menu:require('./icons/menu.png'),
    homeicon:require('./icons/homeicon.png'),
    favourites:require('./icons/favourites.png'),
    accountSelected:require('./icons/accountSel.png'),
    menuSelected:require('./icons/menuSelected.png'),
    star:require('./icons/star.png'),
    home3:require('./icons/home.png'),
    msg:require('./icons/msg.png'),
    bell:require('./icons/bell.png'),
    plus:require('./icons/plus.png'),
    search:require('./icons/search.png'),
    nochat:require('./icons/nochat.png'),
    circleplus:require('./icons/circleplus.png'),
    users:require('./icons/users.png'),
    louds:require('./icons/louds.png'),
    back:require('./icons/back.png'),
    noresult:require('./icons/noResultFoundText.png'),
    more:require('./icons/more.png'),
    plane:require('./icons/plane.png'),
    eye:require('./icons/eye.png'),
    delete:require('./icons/delete.png'),
    unpin:require('./icons/pin.png'),
    reply:require('./icons/reply.png'),
    forward:require('./icons/forward.png'),
    copy:require('./icons/copy.png'),
    star1:require('./icons/star1.png'),
    edit:require('./icons/edit-text.png'),
    telegram:require('./icons/telegram.png'),
    comment:require('./icons/comment.png'),
    calls:require('./icons/calls.png'),
    user2:require('./icons/user2.png'),
  };
  
  
  export default Icons;